/*

 BACKGROUNDTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 28

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BackgroundTilesBank 0

/* Super Gameboy palette 0 */
#define BackgroundTilesSGBPal0c0 6076
#define BackgroundTilesSGBPal0c1 8935
#define BackgroundTilesSGBPal0c2 6596
#define BackgroundTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BackgroundTilesSGBPal1c0 6076
#define BackgroundTilesSGBPal1c1 8935
#define BackgroundTilesSGBPal1c2 6596
#define BackgroundTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BackgroundTilesSGBPal2c0 6076
#define BackgroundTilesSGBPal2c1 8935
#define BackgroundTilesSGBPal2c2 6596
#define BackgroundTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BackgroundTilesSGBPal3c0 6076
#define BackgroundTilesSGBPal3c1 8935
#define BackgroundTilesSGBPal3c2 6596
#define BackgroundTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BackgroundTilesCGBPal0c0 32767
#define BackgroundTilesCGBPal0c1 21140
#define BackgroundTilesCGBPal0c2 10570
#define BackgroundTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define BackgroundTilesCGBPal1c0 32767
#define BackgroundTilesCGBPal1c1 27040
#define BackgroundTilesCGBPal1c2 21140
#define BackgroundTilesCGBPal1c3 16703

/* Gameboy Color palette 2 */
#define BackgroundTilesCGBPal2c0 32767
#define BackgroundTilesCGBPal2c1 28695
#define BackgroundTilesCGBPal2c2 21140
#define BackgroundTilesCGBPal2c3 850

/* Gameboy Color palette 3 */
#define BackgroundTilesCGBPal3c0 32767
#define BackgroundTilesCGBPal3c1 21140
#define BackgroundTilesCGBPal3c2 482
#define BackgroundTilesCGBPal3c3 1347

/* Gameboy Color palette 4 */
#define BackgroundTilesCGBPal4c0 32767
#define BackgroundTilesCGBPal4c1 21140
#define BackgroundTilesCGBPal4c2 10570
#define BackgroundTilesCGBPal4c3 31

/* Gameboy Color palette 5 */
#define BackgroundTilesCGBPal5c0 23542
#define BackgroundTilesCGBPal5c1 8935
#define BackgroundTilesCGBPal5c2 6596
#define BackgroundTilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define BackgroundTilesCGBPal6c0 6076
#define BackgroundTilesCGBPal6c1 8935
#define BackgroundTilesCGBPal6c2 6596
#define BackgroundTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BackgroundTilesCGBPal7c0 6076
#define BackgroundTilesCGBPal7c1 8935
#define BackgroundTilesCGBPal7c2 6596
#define BackgroundTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char BackgroundTilesCGB[];
/* Start of tile array. */
extern unsigned char BackgroundTiles[];

/* End of BACKGROUNDTILES.H */
