/*

 GAMEBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Bruker\Documents\Programmering\gameboy-development\programs\minesweeper\tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GameBackgroundWidth 20
#define GameBackgroundHeight 18
#define GameBackgroundBank 0

#define GameBackground GameBackgroundPLN0
extern unsigned char GameBackgroundPLN0[];
extern unsigned char GameBackgroundPLN1[];

/* End of GAMEBACKGROUND.H */
